import { randomBytes } from "node:crypto";
import { createReadStream } from "node:fs";
import { mkdir } from "node:fs/promises";
import { homedir } from "node:os";
import { resolve } from "node:path";
import { createInterface } from "node:readline/promises";
import { Writable } from "node:stream";
import { readEnvFile, writePrivateEnvFile, type EnvValues } from "./env-file.ts";

const projectRoot = resolve(import.meta.dir, "..");
const envPath = process.env.OPENHOME_GPT_ENV_FILE
  ? resolve(process.env.OPENHOME_GPT_ENV_FILE)
  : resolve(projectRoot, ".env");
const existing = await readEnvFile(envPath);
const nonInteractive = process.argv.includes("--non-interactive");

console.log("\nOpenHome GPT Live setup\n");
console.log("This keeps ChatGPT credentials on this computer and live audio on the DevKit.");
console.log("Press Enter to keep a value shown in brackets.\n");

const terminalInput = nonInteractive
  ? undefined
  : !process.stdin.isTTY ? createReadStream("/dev/tty") : process.stdin;
let mutePromptOutput = false;
const promptOutput = new Writable({
  write(chunk, _encoding, callback) {
    if (!mutePromptOutput) process.stdout.write(chunk);
    callback();
  },
});
const prompts = terminalInput
  ? createInterface({ input: terminalInput, output: promptOutput, terminal: true })
  : undefined;

try {
  const email = await requiredValue(
    "ChatGPT account email",
    configured("APP_ALLOWED_CHATGPT_EMAIL"),
    validateEmail,
  );
  const publicBaseUrlInput = await requiredValue(
    "Stable public HTTPS URL (for example https://voice.example.com)",
    configured("PUBLIC_BASE_URL"),
    validatePublicBaseUrl,
  );
  const publicBaseUrl = new URL(publicBaseUrlInput).origin;
  const workspaceDefault = configured("CODEX_WORKSPACE") || resolve(homedir(), "Code", "Juniper");
  const workspace = resolve(expandHome(await requiredValue(
    "Folder Codex may work in",
    workspaceDefault,
    (value) => value.trim() ? undefined : "Enter a folder path.",
  )));
  const access = await chooseAccessMode(configured("CODEX_MAC_CONTROL") || "disabled");
  const openHomeApiKey = await optionalSecret(
    "OpenHome API key (optional; enables account tools and automatic Ability upload)",
    configured("OPENHOME_API_KEY"),
  );

  if (access === "full") {
    console.log("\nFull Access lets voice-initiated Codex tasks control this computer without approval.");
    if (!nonInteractive) {
      const confirmation = await prompts!.question("Type FULL ACCESS to confirm: ");
      if (confirmation.trim() !== "FULL ACCESS") throw new Error("Full Access was not confirmed.");
    } else if (process.env.OPENHOME_GPT_LIVE_ACCEPT_FULL_ACCESS !== "1") {
      throw new Error("Set OPENHOME_GPT_LIVE_ACCEPT_FULL_ACCESS=1 for non-interactive Full Access setup.");
    }
  }

  await mkdir(workspace, { recursive: true });
  const values: EnvValues = {
    LWC_SECRET: configured("LWC_SECRET") || randomBytes(32).toString("hex"),
    DEVKIT_BOOTSTRAP_TOKEN: configured("DEVKIT_BOOTSTRAP_TOKEN") || randomBytes(32).toString("hex"),
    PUBLIC_BASE_URL: publicBaseUrl,
    OPENHOME_GPT_DATA_DIR: configured("OPENHOME_GPT_DATA_DIR") || "./data",
    OPENHOME_API_KEY: openHomeApiKey,
    OPENHOME_API_BASE: configured("OPENHOME_API_BASE") || "https://app.openhome.com",
    APP_ALLOWED_CHATGPT_EMAIL: email.toLowerCase(),
    CODEX_WORKSPACE: workspace,
    CODEX_MAC_CONTROL: access,
    GPT_LIVE_PERSONALITY_PROMPT: configured("GPT_LIVE_PERSONALITY_PROMPT"),
    LWC_ALLOWED_MODELS: configured("LWC_ALLOWED_MODELS"),
    LWC_DEFAULT_MODEL: configured("LWC_DEFAULT_MODEL"),
    HOST: "127.0.0.1",
    PORT: configured("PORT") || "3000",
    LWC_ALLOWED_ORIGINS: configured("LWC_ALLOWED_ORIGINS") || publicBaseUrl,
    NODE_ENV: "production",
  };
  await writePrivateEnvFile(envPath, values, [
    "Generated by bun run setup. Keep this file private.",
    "Re-run bun run setup to change values without rotating existing secrets.",
  ]);

  console.log(`\nConfiguration saved to ${envPath}`);
  console.log(`Codex workspace: ${workspace}`);
  console.log(`Codex access: ${access === "disabled" ? "workspace only" : access}`);
  console.log("\nYou will enter these two values in OpenHome:");
  console.log(`  openhome_gpt_live_server_url = ${publicBaseUrl}`);
  console.log(`  openhome_gpt_live_bootstrap_token = ${values.DEVKIT_BOOTSTRAP_TOKEN}`);
  console.log("\nRun `bun run openhome:config` later if you need to see them again.");
} finally {
  prompts?.close();
  if (terminalInput && terminalInput !== process.stdin) terminalInput.close();
}

function configured(name: string): string {
  return process.env[name]?.trim() || existing[name]?.trim() || "";
}

async function requiredValue(
  label: string,
  current: string,
  validate: (value: string) => string | undefined,
): Promise<string> {
  if (nonInteractive) {
    const error = validate(current);
    if (error) throw new Error(`${label}: ${error}`);
    return current;
  }
  while (true) {
    const suffix = current ? ` [${current}]` : "";
    const entered = (await prompts!.question(`${label}${suffix}: `)).trim();
    const value = entered || current;
    const error = validate(value);
    if (!error) return value;
    console.log(`  ${error}`);
  }
}

async function optionalSecret(label: string, current: string): Promise<string> {
  if (nonInteractive) return current;
  const suffix = current ? " [already saved; Enter keeps it]" : " [Enter to skip]";
  process.stdout.write(`${label}${suffix}: `);
  mutePromptOutput = true;
  const entered = (await prompts!.question("")).trim();
  mutePromptOutput = false;
  process.stdout.write("\n");
  return entered || current;
}

async function chooseAccessMode(current: string): Promise<"disabled" | "confirmed" | "full"> {
  const normalized = ["disabled", "confirmed", "full"].includes(current) ? current : "disabled";
  if (nonInteractive) return normalized as "disabled" | "confirmed" | "full";
  console.log("\nCodex access:");
  console.log("  1. Workspace only (recommended)");
  console.log("  2. Ask in the paired browser control page before controlling the Mac");
  console.log("  3. Full Access without approval");
  const defaultChoice = normalized === "confirmed" ? "2" : normalized === "full" ? "3" : "1";
  const answer = (await prompts!.question(`Choose 1, 2, or 3 [${defaultChoice}]: `)).trim() || defaultChoice;
  if (answer === "1") return "disabled";
  if (answer === "2") return "confirmed";
  if (answer === "3") return "full";
  console.log("  Please choose 1, 2, or 3.");
  return chooseAccessMode(normalized);
}

function validateEmail(value: string): string | undefined {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)
    ? undefined
    : "Enter the email address used by the ChatGPT account that will authorize the speaker.";
}

function validatePublicBaseUrl(value: string): string | undefined {
  try {
    const url = new URL(value);
    if (url.protocol !== "https:") return "Use an HTTPS URL.";
    if (url.username || url.password || url.search || url.hash) return "Use only the public origin, without credentials or query text.";
    if (url.pathname !== "/") return "Use only the origin, without a path (for example https://voice.example.com).";
    return undefined;
  } catch {
    return "Enter a complete URL such as https://voice.example.com.";
  }
}

function expandHome(value: string): string {
  return value === "~" ? homedir() : value.startsWith("~/") ? resolve(homedir(), value.slice(2)) : value;
}
