import { createReadStream } from "node:fs";
import { resolve } from "node:path";
import { createInterface } from "node:readline/promises";
import { Writable } from "node:stream";
import { AgentMailClient } from "../src/agentmail-client.ts";
import { readEnvFile, writePrivateEnvFile } from "./env-file.ts";

const projectRoot = resolve(import.meta.dir, "..");
const envPath = process.env.OPENHOME_GPT_ENV_FILE
  ? resolve(process.env.OPENHOME_GPT_ENV_FILE)
  : resolve(projectRoot, ".env");
const existing = await readEnvFile(envPath);
const options = parseOptions(process.argv.slice(2));

if (options.help) {
  printHelp();
  process.exit(0);
}

if (options.disable) {
  await writePrivateEnvFile(envPath, {
    ...existing,
    AGENTMAIL_API_KEY: "",
    AGENTMAIL_INBOX: "",
  }, comments());
  console.log("AgentMail voice email is disabled. Other OpenHome configuration was preserved.");
  process.exit(0);
}

console.log("\nOpenHome AgentMail setup\n");
console.log("This selects one existing AgentMail inbox for autonomous voice email sends.");
console.log("An inbox-scoped key needs message_send; broader keys also need inbox_read for validation.");
console.log("The API key stays in the host's private .env file and is never sent to the DevKit.\n");

const terminalInput = options.nonInteractive
  ? undefined
  : !process.stdin.isTTY ? createReadStream("/dev/tty") : process.stdin;
let mutePromptOutput = false;
const promptOutput = new Writable({
  write(chunk, _encoding, callback) {
    if (!mutePromptOutput) process.stdout.write(chunk);
    callback();
  },
});
const prompts = terminalInput
  ? createInterface({ input: terminalInput, output: promptOutput, terminal: true })
  : undefined;

try {
  const currentApiKey = process.env.AGENTMAIL_API_KEY?.trim()
    || existing.AGENTMAIL_API_KEY?.trim()
    || "";
  const currentInbox = options.inbox
    ?? process.env.AGENTMAIL_INBOX?.trim()
    ?? existing.AGENTMAIL_INBOX?.trim()
    ?? "";
  const apiKey = options.nonInteractive
    ? currentApiKey
    : await requiredSecret("AgentMail API key", currentApiKey);
  const inbox = options.nonInteractive
    ? currentInbox
    : await requiredValue("AgentMail sender inbox address", currentInbox);

  if (!apiKey) throw new Error("AGENTMAIL_API_KEY is required.");
  if (!inbox) throw new Error("AGENTMAIL_INBOX is required.");

  const client = new AgentMailClient({
    apiKey,
    inbox,
    baseUrl: process.env.AGENTMAIL_API_BASE?.trim() || existing.AGENTMAIL_API_BASE?.trim(),
  });
  const verified = await client.verifyInbox();
  await writePrivateEnvFile(envPath, {
    ...existing,
    AGENTMAIL_API_KEY: apiKey,
    AGENTMAIL_INBOX: verified.email,
  }, comments());

  console.log("\nAgentMail is ready for GPT Live voice email.");
  console.log(`Selected sender: ${verified.email}`);
  console.log("Restart the OpenHome GPT Live service, then test one message with your voice.");
} finally {
  prompts?.close();
  if (terminalInput && terminalInput !== process.stdin) terminalInput.close();
}

async function requiredSecret(label: string, current: string): Promise<string> {
  const suffix = current ? " [already saved; Enter keeps it]" : "";
  process.stdout.write(`${label}${suffix}: `);
  mutePromptOutput = true;
  const entered = (await prompts!.question("")).trim();
  mutePromptOutput = false;
  process.stdout.write("\n");
  return entered || current;
}

async function requiredValue(label: string, current: string): Promise<string> {
  while (true) {
    const suffix = current ? ` [${current}]` : "";
    const value = (await prompts!.question(`${label}${suffix}: `)).trim() || current;
    if (/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) return value;
    console.log("  Enter one complete AgentMail inbox email address.");
  }
}

function parseOptions(values: string[]): {
  help: boolean;
  nonInteractive: boolean;
  disable: boolean;
  inbox?: string;
} {
  const parsed = { help: false, nonInteractive: false, disable: false } as ReturnType<typeof parseOptions>;
  for (let index = 0; index < values.length; index += 1) {
    const value = values[index]!;
    const next = () => {
      const found = values[++index];
      if (!found) throw new TypeError(`${value} requires a value.`);
      return found;
    };
    if (value === "--help" || value === "-h") parsed.help = true;
    else if (value === "--non-interactive") parsed.nonInteractive = true;
    else if (value === "--disable") parsed.disable = true;
    else if (value === "--inbox") parsed.inbox = next();
    else if (value.startsWith("--inbox=")) parsed.inbox = value.slice(8);
    else throw new TypeError(`Unknown AgentMail setup option: ${value}.`);
  }
  return parsed;
}

function comments(): string[] {
  return [
    "Generated by OpenHome GPT Live setup. Keep this file private.",
    "Re-run setup commands to change values without rotating unrelated secrets.",
  ];
}

function printHelp(): void {
  console.log(`OpenHome AgentMail setup

Usage:
  bun run agentmail:setup
  bun run agentmail:setup -- --inbox speaker@agentmail.to
  bun run agentmail:setup -- --non-interactive
  bun run agentmail:setup -- --disable

Options:
  --inbox EMAIL        Existing AgentMail inbox selected as the speaker sender
  --non-interactive    Read AGENTMAIL_API_KEY and AGENTMAIL_INBOX without prompting
  --disable            Clear only the AgentMail key and selected inbox
  -h, --help           Show this help

The API key is requested with hidden input. For non-interactive use, set
AGENTMAIL_API_KEY in the environment; never put it in a command-line flag.
Prefer an inbox-scoped key with message_send. An organization- or pod-scoped key
also needs inbox_read so setup can validate the selected address.
`);
}
